variables:
  PYTHON_ENVIRONMENT_PATH: .venv
  PIP_CACHE_DIR: .cache/pip
  FF_ENABLE_JOB_CLEANUP: "true"

stages:
  - environment
  - format
  - build-and-test
  - cleanup

# Create a python env and cache it
# Note: The cache needs to be removed manually in CI if the python environment
# is changed, by clicking "CI/CD - Pipelines - Clear Runner Caches".
configure_python:
  variables:
    GIT_STRATEGY: none
  tags:
    - shell
    - catalyst
  stage: environment
  script:
    - /usr/tce/packages/python/python-3.7.2/bin/virtualenv -p /usr/tce/packages/python/python-3.7.2/bin/python3 ${PYTHON_ENVIRONMENT_PATH}
    - . ${PYTHON_ENVIRONMENT_PATH}/bin/activate
    - PYTHON_EXECUTABLE=$(which python3)
    - ${PYTHON_EXECUTABLE} -m pip install matplotlib pandas numpy glob2
    - ${PYTHON_EXECUTABLE} -m pip install pytest
    - ${PYTHON_EXECUTABLE} -m pip install click==8.0.4
    - ${PYTHON_EXECUTABLE} -m pip install black==21.12b0
    - ${PYTHON_EXECUTABLE} -m pip install flake8==4.0.1
    - ${PYTHON_EXECUTABLE} -m pip install cython multiprocess textX caliper-reader
  cache:
    paths:
      - ${PYTHON_ENVIRONMENT_PATH}
      - ${PIP_CACHE_DIR}

.venv:
  cache:
    paths:
      - ${PYTHON_ENVIRONMENT_PATH}
      - ${PIP_CACHE_DIR}
    policy: pull

lint-format-check:
  tags:
    - shell
    - catalyst
  extends: .venv
  stage: format
  script:
    - . ${PYTHON_ENVIRONMENT_PATH}/bin/activate
    - $(which python3) --version
    - $(which python3) -m flake8 --version
    - $(which python3) -m flake8
    - $(which python3) -m black --check --diff .

check-license-headers:
  tags:
    - shell
    - catalyst
  extends: .venv
  stage: format
  script:
    - . ${PYTHON_ENVIRONMENT_PATH}/bin/activate
    - $(which python3) --version
    - $(which python3) license.py verify

build-and-test-py37:
  tags:
    - shell
    - catalyst
  stage: build-and-test
  extends: .venv
  script:
    - . ${PYTHON_ENVIRONMENT_PATH}/bin/activate
    - $(which python3) -m pip install --ignore-installed --no-deps -r requirements.txt
    - $(which python3) setup.py install
    - PYTHONPATH=. $(which python3) -m pytest
