#.readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  apt_packages:
    - ca-certificates
    - curl
    - gnupg
    - docker-ce-rootless-extras
    - uidmap
    - dbus-user-session
  jobs:
    pre_system_dependencies:
      - install -m 0755 -d /etc/apt/keyrings
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      - chmod a+r /etc/apt/keyrings/docker.gpg
      - echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      - apt-get update
    post_system_dependencies:
      - dockerd-rootless-setuptool.sh install
    pre_build:
      - export XDG_RUNTIME_DIR="$HOME/.docker/run"
      - dockerd-rootless.sh
      - export DOCKER_HOST="unix://$XDG_RUNTIME_DIR/docker.sock"
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: docs/requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
